<?php

return [
    'yaml_path' => base_path('yaml-to-filament'), // default folder for YAML files
    'stubs_path' => __DIR__ . '/../src/Generators/stubs',
    'output_paths' => [
        'models' => app_path(),
        'migrations' => database_path('migrations'),
        'resources' => app_path('Filament/Resources'),
        'panels' => app_path('Filament/Panels'),
        'pages' => app_path('Filament/Pages'),
        'widgets' => app_path('Filament/Widgets'),
        'tables' => app_path('Filament/Tables'),
        'forms' => app_path('Filament/Forms'),
        'layouts' => app_path('Filament/Layouts'),
        'notifications' => app_path('Filament/Notifications'),
        'actions' => app_path('Filament/Actions'),
        'resources' => app_path('Filament/Resources'),
        'settings' => app_path('Filament/Settings'),
        'menus' => app_path('Filament/Menus'),
        'themes' => app_path('Filament/Themes'),
        'translations' => app_path('Filament/Translations'),
        'policies' => app_path('Filament/Policies'),
        'guards' => app_path('Filament/Guards'),
        'providers' => app_path('Filament/Providers'),
        'factories' => app_path('Filament/Factories'),
        'seeds' => app_path('Filament/Seeds'),
        'tests' => app_path('Filament/Tests'),
        'helpers' => app_path('Filament/Helpers'),
        'traits' => app_path('Filament/Traits'),
        'commands' => app_path('Filament/Commands'),
        'listeners' => app_path('Filament/Listeners'),
        'subscribers' => app_path('Filament/Subscribers'),
        'middleware' => app_path('Filament/Middleware'),
        'events' => app_path('Filament/Events'),
        'jobs' => app_path('Filament/Jobs'),
        'queues' => app_path('Filament/Queues'),
        'broadcasts' => app_path('Filament/Broadcasts'),
        'websockets' => app_path('Filament/Websockets'),
        'sockets' => app_path('Filament/Sockets'),
        'channels' => app_path('Filament/Channels'),
        'routes' => app_path('Filament/Routes'),
        'config' => app_path('Filament/Config'),
        'assets' => app_path('Filament/Assets'),
        'views' => app_path('Filament/Views'),
    ],
];
